### ISSUE TITLE
list items don't wrap in ie11

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#26] opened 2016-03-29 01:20 UTC
can be seen on the homepage, must be related to all this flexbox crap since changing percentages on the sidebar yields very unpredictable results. as of now the sidebar is just extended way too far to the right.

**Comment by denjello** [comment] 2016-06-09 14:06
can you please check this again and send me screenshots?

**Comment by Sefux** [comment] 2018-03-13 23:10
cant reproduce... closing

**Closed by Sefux** 2018-03-13 23:10 UTC
Labels: bug
