### ISSUE TITLE
provide cookie fallback when local storage is unavailable

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#29] opened 2016-04-26 20:31 UTC
some browsers (e.g. safari) completely disable local storage in private browsing mode.

we need a cookie fallback when that happens so people are able to log in during the private session.

**Comment by Sefux** [comment] 2018-03-13 23:15
closing because this can not be reproduced. in private mode (safari) the login is possible.

**Closed by Sefux** 2018-03-13 23:15 UTC
Labels: enhancement
